version: '2'
services:
    deliverytools-app:
        image: deliverytools
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://deliverytools-mysql:3306/deliverytools?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    deliverytools-mysql:
        extends:
            file: mysql.yml
            service: deliverytools-mysql
